version: '3.9'
services: 
  web: 
    container_name: nginx
    image: nginx:latest
    ports: 
      - 80:80
    volumes:
      - "../../nginx/templates:/etc/nginx/templates"
        #      - "../nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../../nginx/html:/usr/share/nginx/html:ro"
    command: [nginx-debug, '-g', 'daemon off;']
    networks: 
      - net
  sonarqube: 
    container_name: sonarqube
    image: sonarqube:lts
    depends_on: 
      - web
    ports: # host_port:container_port 
      - 9000:9000
    volumes: 
      - "../../sonarqube/data:/opt/sonarqube/data"
      - "../../sonarqube/logs:/opt/sonarqube/logs"
      - "../../sonarqube/extensions:/opt/sonarqube/extensions"
    networks: 
      - net
  jenkins: 
    container_name: jenkins
    image: jenkins/jenkins
    depends_on: 
      - web
      - sonarqube
    ports: # host_port:container_port
      - 8080:8080
    volumes: # host_path:container_path
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks: 
      - net
networks: 
  net: 
